### ISSUE TITLE
Use IPFS directly

### ISSUE THREAD

**Issue by sr229** [ClarityCafe/Aya#15]
I think adding even more complexity to the stack that I introduced in #1 would make it unmaintainable and unusable. I figured out its possible to just use IPFS as-is, so we're getting rid of the Ethereum Backend.

**Comment by DonaldTsang** [comment]
What is the Ethereum backend originally for?

**Comment by sr229** [comment]
It was used to store IPFS hashes but we figured to use a classic DB for this instead. I would revisit this in the near future.

**Comment by sr229** [comment]
We're now using IPFS directly so this could be marked done :3c
