### ISSUE TITLE
Info: relations with other boorus

### ISSUE THREAD

**Issue by DonaldTsang** [ClarityCafe/Aya#19]
There are other boorus like:
- https://github.com/Kycklingar/PBooru (IPFS based with TOR and I2P endpoints)
- https://github.com/hydrusnetwork/hydrus (IPFS, for personal use)

What are the differences, and if possible, any communication channels for collaboration?
(Preferably Discord and Telegram)

**Comment by sr229** [comment]
See my reply on #20

**Comment by Ovyerus** [comment]
For communication we have an org Discord server.
